# Generated by Django 5.0.2 on 2024-02-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='male',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
