# Generated by Django 5.0.2 on 2024-02-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='male',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
